"""Utility function to generate property objects."""

from singer_sdk import typing as th  # JSON Schema typing helpers


def generate_language_objects():
    LANGUAGUES = [
        "C"
        "JavaScript"
        "C++"
        "PHP"
        "HTML"
        "Java"
        "Python"
        "CSS"
        "Assembly"
        "C#"
        "Go"
        "Jupyter Notebook"
        "Objective-C"
        "Ruby"
        "TypeScript"
        "Shell"
        "Perl"
        "Makefile"
        "Visual Basic"
        "Web Ontology Language"
        "OpenEdge ABL"
        "Scala"
        "VHDL"
        "Emacs Lisp"
        "Erlang"
        "Lua"
        "D"
        "Ada"
        "Groff"
        "Swift"
        "PLSQL"
        "TeX"
        "PLpgSQL"
        "Roff"
        "Mathematica"
        "IDL"
        "Logos"
        "Objective-C++"
        "FORTRAN"
        "TSQL"
        "Rust"
        "DM"
        "CoffeeScript"
        "Haskell"
        "Pascal"
        "XSLT"
        "Fortran"
        "Matlab"
        "R"
        "Eagle"
        "CMake"
        "LLVM"
        "Smali"
        "Groovy"
        "Verilog"
        "Smarty"
        "M"
        "PowerShell"
        "Tcl"
        "OCaml"
        "ActionScript"
        "Prolog"
        "Dart"
        "Game Maker Language"
        "PostScript"
        "Gettext Catalog"
        "SQLPL"
        "Gnuplot"
        "Scheme"
        "Scilab"
        "F#"
        "Clojure"
        "Common Lisp"
        "ASP"
        "Batchfile"
        "MATLAB"
        "Cuda"
        "Visual Basic .NET"
        "VimL"
        "Smalltalk"
        "GLSL"
        "Coq"
        "Vim script"
        "SQF"
        "Kotlin"
        "G-code"
        "Yacc"
        "Lex"
        "M4"
        "GAP"
        "Gherkin"
        "SourcePawn"
        "Genshi"
        "Processing"
        "KiCad"
        "QML"
        "Eiffel"
        "Cucumber"
        "Arc"
        "Perl6"
        "Rich Text Format"
        "AGS Script"
        "Arduino"
        "Haxe"
        "SQL"
    ]

    return [th.Property(language, th.IntegerType) for language in LANGUAGUES]
